channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.12.*
  - ipykernel=6.29.*
  # - cuda-toolkit=13.* # Install cuBLAS
  # - cudnn=9.*
  - pytorch=2.4.* # =*cuda* # Might need to specifically request cuda version
  - torchaudio=2.4.*
  - pip>=23
